blank_issues_enabled: false
contact_links:
  - name: ğŸ“¨ sesim ê¹ƒí—ˆë¸Œ í”„ë¡œí•„
    url: https://github.com/sesim/
    about: Please ask and answer questions here.
  - name: ğŸŒ sesim í”„ë¡œì íŠ¸
    url: https://github.com/users/sesim/projects/4
    about: Please report security vulnerabilities here.
